### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by Honigbrot** [yenoiwesa/homebridge-connexoon#77] opened 2023-02-24 07:53 UTC
Thank you for your plugin!
I've been using the Homebridge-TaHoma plugin before, but i was curious about the option to use the "my position" of my shutters.
I can't seem to get it working though.
The Plugin loads and seems to log in just fine but doesn't add any devices. Am I missing something?

[My TaHoma Hub] Initializing Connexoon platform...
[My TaHoma Hub] Connexoon Init
[My TaHoma Hub] Starting polling for Connexoon accessory state every 10 minute(s)

My Config:
{
            "platform": "Connexoon",
            "name": "My TaHoma Hub",
            "username": "XXXX",
            "password": "XXXX",
            "service": "TaHoma"
        }

The Config I've been using for Homebridge-TaHoma:
{
            "name": "TaHoma",
            "service": "somfy_europe",
            "user": "XXXX",
            "password": "XXXX",
            "platform": "Tahoma"
        }

**Comment by yenoiwesa** [comment] 2023-02-24 08:06
The configuration seems alright. Can you restart your homebridge in debug mode to see the extra logging?

**Comment by Honigbrot** [comment] 2023-02-24 08:13
Sure!
[24.2.2023, 09:10:59] [My Connexoon Hub] Logged in successfully via Somfy OAuth
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Shutter
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Shutter
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Shutter
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Light
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type ProtocolGateway
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type ProtocolGateway
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type ProtocolGateway
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Shutter
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Shutter
[24.2.2023, 09:11:04] [My Connexoon Hub] Ignored device of type Shutter
[24.2.2023, 09:11:04] [My Connexoon Hub] Found 0 devices
[24.2.2023, 09:11:04] [My Connexoon Hub] Starting polling for Connexoon accessory state every 10 minute(s)

I still have the Homebridge-Tahoma Plugin installed and configured, but deactivated in Homebridge. Could that be a problem?
The Shutters I have installed use the RTS protocol and I'm using the Somfy Connectivity Kit.

**Comment by yenoiwesa** [comment] 2023-02-24 08:36
Having the other plugin shouldn't be a problem.

But here the issue is the type of your devices. My plugin doesn't support the type `Shutter`, it only supports the following accessory types:

```js
    Awning: [WindowCovering],
    Curtain: [WindowCovering],
    ExteriorScreen: [WindowCovering],
    ExteriorVenetianBlind: [WindowCovering],
    Generic: [WindowCovering],
    Pergola: [WindowCovering],
    RollerShutter: [WindowCovering],
    Screen: [WindowCovering],
    SwingingShutter: [WindowCovering],
    VenetianBlind: [WindowCovering],
```

Could you try to add: `Shutter: [WindowCovering],` to your local file in `node_modules/homebridge-connexoon/src/services-mapping.js` ([services-mapping.js](https://github.com/yenoiwesa/homebridge-connexoon/tree/master/src/services-mapping.js)) and then restart homebridge see if it does work?

**Comment by Honigbrot** [comment] 2023-02-24 09:48
That did the trick - thank you so much!

**Comment by yenoiwesa** [comment] 2023-02-24 11:28
Lol well we shouldn't close the issue, now that we know it works I need to add that mapping to the code and publish a new version of the plug-in, otherwise it's only fixed for you.

**Comment by yenoiwesa** [comment] 2023-02-25 00:22
@Honigbrot version `2.2.4` of the plugin (latest) has just been released with this addition. Please upgrade to the latest version.

Thanks!

**Closed as completed by yenoiwesa** 2023-02-25 00:22 UTC
