### ISSUE TITLE
Spurious error messages (may be related to Homebrodge beta)

### ISSUE THREAD

**Issue by sddgit** [yenoiwesa/homebridge-connexoon#27] opened 2021-02-07 10:13 UTC
I recently updated to Homebridge v1.3.0-beta.53 to try to fix something unrelated. I now see the following when this plugin starts (in red) that I don't _think_ were there before the beta::

```log
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Elephant Blind
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Elephant Blind
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 4
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 4
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 3
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 3
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Lounge 3
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Lounge 3
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 1
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 1
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 2
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Kitchen 2
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Lounge 1
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Lounge 1
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Lounge 2
[2/7/2021, 9:07:55 PM] [Connexoon] No device is associated to Lounge 2
```

Everything still seems to work, but I thought I'd mention it!

**Comment by yenoiwesa** [comment] 2021-02-07 23:06
Hey @sddgit 👋 

These messages mean that your devices were loaded from the Homebridge accessory cache at start up because they were defined before, but somehow no device could be associated to them once the plugin reached the Somfy server to retrieve the list of devices and rehydrate the cached accessories.

This might be due to the beta version of Homebridge that changed the unique IDs of cached accessories or something of that sort.
These unlinked cached accessories are automatically cleaned up.

The only impact you will have is that your scenes and automations might have lost the Somfy accessories and you will have to remap/recreate them.

If you restart your Homebridge server on this same version, these messages should not appear. If you could confirm that then everything is fine.

Let me know if there is anything more you'd like to know, otherwise I will close the issue.

Cheers.

**Comment by sddgit** [comment] 2021-02-08 00:59
Thank you very much for the reply.

The messages are always there whenever I restart Homebridge (on the same beta version). If I go into Homebridge settings, and “Remove single cached accessory”, the blinds are all listed (and only once each). All my existing scenes in the Home app are working fine, without having changed anything. So something seems a bit awry...

**Comment by yenoiwesa** [comment] 2021-02-08 01:02
I am not sure to be honest. I don't officially support beta versions of Homebridge so it's pretty much at your own risk :-S

**Comment by sddgit** [comment] 2021-02-08 02:07
Sure, understood. I guess if it’s a continuing problem once this is out of beta you might be able to take it further. Thanks again.

**Comment by yenoiwesa** [comment] 2021-02-14 07:27
Hey @sddgit 👋 

So I have been running Homebridge `v1.3.0-test.6` and have not been able to reproduce this behaviour. Could you please reset your accessory cache and make sure it's not related to your local configuration?

**Comment by sddgit** [comment] 2021-02-14 10:28
I recently reverted to V1.1.7, and the messages aren't there. I was running v1.3.0-beta.53 - are you saying you're on beta 6?

When I go back to beta (it seems to fix some mDNS weirdness), do you mean to remove all my blinds using "Remove Single Cached Accessory" in HB settings?

**Comment by yenoiwesa** [comment] 2021-02-14 11:41
I installed the latest beta version from npm, which is `1.3.0-beta.57`, but the logging from Homebridge itself printed `Homebridge v1.3.0-test.6`,

Either way, this very last version did not present the problem you mentioned.

I am not sure what HB settings are, are you using a UI software on top of Homebridge?
You can just run a new instance of Homebridge targeting a clean homebridge home directory if you wish to test without cleaning your current accessory cache.

**Comment by sddgit** [comment] 2021-02-15 11:28
I’ve tried beta 57, and I still get the errors. Here's another log snippet:

[2/15/2021, 8:38:32 PM] [Connexoon] Initializing Connexoon platform...
[2/15/2021, 8:38:32 PM] [Connexoon] Connexoon Init
[2/15/2021, 8:38:32 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[2/15/2021, 8:38:32 PM] [Lounge] Initializing HarmonyHubWebSocket platform...
[2/15/2021, 8:38:32 PM] [Lounge] HarmonyPlatform Init
[2/15/2021, 8:38:32 PM] [Big Ass Fan] Master Bedroom Fan Configure Accessory 71fc0cee-2db1-4630-b019-1040a73f2e1a
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Elephant Blind
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Kitchen 4
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Kitchen 3
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Lounge 3
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Kitchen 1
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Kitchen 2
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Lounge 1
[2/15/2021, 8:38:32 PM] [Connexoon] Restoring cached accessory Lounge 2
[2/15/2021, 8:38:32 PM] [TuyaWebPlatform] Loading accessory from cache: smart fan
[2/15/2021, 8:38:32 PM] [Big Ass Fan] Ems Bedroom Fan Configure Accessory dda20c6c-7379-43a7-ba54-d8f491287409
[2/15/2021, 8:38:32 PM] [Big Ass Fan] DidFinishLaunching
[2/15/2021, 8:38:32 PM] [Lounge] DidFinishLaunching
[2/15/2021, 8:38:32 PM] [Lounge] (Lounge)INFO - Loading activities...
[2/15/2021, 8:38:32 PM] [Lounge] (Kitchen)INFO - Loading activities...
[2/15/2021, 8:38:32 PM] [Lounge] (Theatre)INFO - Loading activities...
[2/15/2021, 8:38:32 PM] [Lounge] (Studio)INFO - Loading activities...
[2/15/2021, 8:38:32 PM] [Lounge] (Master Bedroom)INFO - Loading activities...
Preparing Advertiser for 'Homebridge 5CD6 5FD4' using ciao backend!
Setup Payload:
X-HM://0024YD5L52KD9
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxxxxxxxx │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 5CD6 5FD4' using ciao backend!
[2/15/2021, 8:38:32 PM] Homebridge v1.3.0-beta.57 (Homebridge 5CD6) is running on port 51115.
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Elephant Blind
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Elephant Blind
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 4
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 4
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 3
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 3
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Lounge 3
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Lounge 3
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 1
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 1
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 2
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Kitchen 2
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Lounge 1
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Lounge 1
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Lounge 2
[2/15/2021, 8:38:33 PM] [Connexoon] No device is associated to Lounge 2

I use https://github.com/oznu/homebridge-config-ui-x as a UI. That's what has Settings that allow you to individually delete cached accessories. Are there any ramifications in doing that? Will they just get rebuilt at the next startup of your plugin?

Using this beta, I'm seeing a lot of refreshing of accessory statuses. That is, every few minutes (sometimes longer) I can see Conexooon log messages (current and target position lines for each blind) that indicate Homekit has asked for status. There are log entries for other plugins at the same time. When I revert to V1.1.7, this doesn't happen. Are you able to check your HB logs to see if you get entries even though you're not actively using the Home app? There's also heaps of mDNS traffic when using the bonjour-hap advertiser, less when using the new ciao one. Grrrr....

**Comment by yenoiwesa** [comment] 2021-02-15 11:36
I have been testing the plugin in isolation against the beta with no such issues.

I suggest you entirely delete/reset/clear your Homebridge accessory cache and try again.

**Comment by sddgit** [comment] 2021-02-15 23:45
It’s so weird. Back on 1.1.7, and the log is completely empty all night. Go on to the beta and it’s full of log entries from your and other plugins indicating that Homekit has asked for a status update. 

I will try removing the Connexoon accessories from the cache to see if that clears up the error messages when on the beta. Thanks for the help.

**Comment by yenoiwesa** [comment] 2021-02-16 05:44
I am afraid there isn't much more I can do to help you with this.
I will close this issue since it doesn't seem to be related to this plugin and I was unable to reproduce the behaviour reported.

Good luck with your Homebridge setup though and I hope you get to the bottom of it!

**Closed as completed by yenoiwesa** 2021-02-16 05:44 UTC
